apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-api
  namespace: health-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: health-api
  template:
    metadata:
      labels:
        app: health-api
    spec:
      containers:
      - name: health-api
        image: ghcr.io/uvinodk/health-api-service:latest
        ports:
        - containerPort: 8000
